# Generated by Django 4.1.5 on 2023-07-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
