# Generated by Django 4.1.5 on 2023-07-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.image'),
        ),
    ]
