# Generated by Django 4.2.3 on 2023-07-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_history_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], max_length=10),
        ),
    ]
